<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Marketplace.Domain\Marketplace.Domain.csproj" />
    <ProjectReference Include="..\Domain\Marketplace.ValueObjects\Marketplace.ValueObjects.csproj" />
  </ItemGroup>

</Project>
